import { Inter } from "next/font/google";
import "../../public/sass/global.scss"
import "../../public/sass/helper/base.scss"
import "../../public/sass/helper/helper.scss"
import "../../public/sass/helper/reset.scss"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>{children}
        <ToastContainer />
      </body>
    </html>
  );
}
